global using BasicBlazorLibrary.Components.BaseClasses;
global using BasicBlazorLibrary.Components.Basic;
global using BasicBlazorLibrary.Helpers;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses; //so i can have access to the exceptions when needed.
global using CommonBasicLibraries.CollectionClasses;
global using Microsoft.AspNetCore.Components;
global using Microsoft.Extensions.DependencyInjection;
global using Phase05PowerPinsOutputAugmentation.Components;
global using bb1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using cc1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;
global using css1 = BasicBlazorLibrary.CssHelpers.AllCssClasses; //so i can have intellisense completely from c# if i want.
global using ff1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileFunctions;
global using Phase05PowerPinsOutputAugmentation.Services.Crops;
global using Phase05PowerPinsOutputAugmentation.Services.Trees;
global using Phase05PowerPinsOutputAugmentation.Services.Animals;
global using Phase05PowerPinsOutputAugmentation.Services.Workshops;
global using Phase05PowerPinsOutputAugmentation.Services.Workers;
global using Phase05PowerPinsOutputAugmentation.Services.Worksites;
global using Phase05PowerPinsOutputAugmentation;
global using CommonBasicLibraries.BasicUIProcesses;
global using DocumentDbLibrary;
global using CommonBasicLibraries.DatabaseHelpers.AbstractStaticInterfaces;
global using dd1 = CommonBasicLibraries.DatabaseHelpers.MiscClasses.GlobalClass;
global using SQLiteHelperLibraries;
global using mm1 = Phase05PowerPinsOutputAugmentation.DataAccess.Core.MainDatabase;
global using Phase05PowerPinsOutputAugmentation.Quests;
global using Phase05PowerPinsOutputAugmentation.Services.Core;
global using Phase05PowerPinsOutputAugmentation.Services.Balance;
global using Phase05PowerPinsOutputAugmentation.Services.Inventory;
global using Phase05PowerPinsOutputAugmentation.DataAccess.Inventory;
global using Phase05PowerPinsOutputAugmentation.Utilities;
global using Phase05PowerPinsOutputAugmentation.Services.Upgrades;
global using Phase05PowerPinsOutputAugmentation.Services.Progression;
global using Phase05PowerPinsOutputAugmentation.Services.Catalog;
global using Phase05PowerPinsOutputAugmentation.Services.Store;
global using Phase05PowerPinsOutputAugmentation.Services.Items;
global using Phase05PowerPinsOutputAugmentation.Services.InstantUnlimited;
global using Phase05PowerPinsOutputAugmentation.Services.TimedBoosts;
global using Phase05PowerPinsOutputAugmentation.Services.OutputAugmentation;
