global using BasicBlazorLibrary.Components.BaseClasses;
global using BasicBlazorLibrary.Components.Basic;
global using BasicBlazorLibrary.Helpers;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses; //so i can have access to the exceptions when needed.
global using CommonBasicLibraries.CollectionClasses;
global using Microsoft.AspNetCore.Components;
global using Microsoft.Extensions.DependencyInjection;
global using Phase08AutoCompleteSingle.Components;
global using bb1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using cc1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;
global using css1 = BasicBlazorLibrary.CssHelpers.AllCssClasses; //so i can have intellisense completely from c# if i want.
global using ff1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileFunctions;
global using Phase08AutoCompleteSingle.Services.Crops;
global using Phase08AutoCompleteSingle.Services.Trees;
global using Phase08AutoCompleteSingle.Services.Animals;
global using Phase08AutoCompleteSingle.Services.Workshops;
global using Phase08AutoCompleteSingle.Services.Workers;
global using Phase08AutoCompleteSingle.Services.Worksites;
global using Phase08AutoCompleteSingle;
global using CommonBasicLibraries.BasicUIProcesses;
global using DocumentDbLibrary;
global using CommonBasicLibraries.DatabaseHelpers.AbstractStaticInterfaces;
global using dd1 = CommonBasicLibraries.DatabaseHelpers.MiscClasses.GlobalClass;
global using SQLiteHelperLibraries;
global using mm1 = Phase08AutoCompleteSingle.DataAccess.Core.MainDatabase;
global using Phase08AutoCompleteSingle.Quests;
global using Phase08AutoCompleteSingle.Services.Core;
global using Phase08AutoCompleteSingle.Services.Balance;
global using Phase08AutoCompleteSingle.Services.Inventory;
global using Phase08AutoCompleteSingle.DataAccess.Inventory;
global using Phase08AutoCompleteSingle.Utilities;
global using Phase08AutoCompleteSingle.Services.Upgrades;
global using Phase08AutoCompleteSingle.Services.Progression;
global using Phase08AutoCompleteSingle.Services.Catalog;
global using Phase08AutoCompleteSingle.Services.Store;
global using Phase08AutoCompleteSingle.Services.Items;
global using Phase08AutoCompleteSingle.Services.InstantUnlimited;
global using Phase08AutoCompleteSingle.Services.TimedBoosts;
global using Phase08AutoCompleteSingle.Services.OutputAugmentation;
global using rs1 = Phase08AutoCompleteSingle.Utilities.RandomUtilities;