global using BasicBlazorLibrary.Components.BaseClasses;
global using BasicBlazorLibrary.Components.Basic;
global using BasicBlazorLibrary.Helpers;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses; //so i can have access to the exceptions when needed.
global using CommonBasicLibraries.CollectionClasses;
global using Microsoft.AspNetCore.Components;
global using Microsoft.Extensions.DependencyInjection;
global using Phase11MVP3.Components;
global using bb1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using cc1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;
global using css1 = BasicBlazorLibrary.CssHelpers.AllCssClasses; //so i can have intellisense completely from c# if i want.
global using ff1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileFunctions;
global using Phase11MVP3.Services.Crops;
global using Phase11MVP3.Services.Trees;
global using Phase11MVP3.Services.Animals;
global using Phase11MVP3.Services.Workshops;
global using Phase11MVP3.Services.Workers;
global using Phase11MVP3.Services.Worksites;
global using Phase11MVP3;
global using CommonBasicLibraries.BasicUIProcesses;
global using DocumentDbLibrary;
global using CommonBasicLibraries.DatabaseHelpers.AbstractStaticInterfaces;
global using dd1 = CommonBasicLibraries.DatabaseHelpers.MiscClasses.GlobalClass;
global using SQLiteHelperLibraries;
global using mm1 = Phase11MVP3.DataAccess.Core.MainDatabase;
global using Phase11MVP3.Quests;
global using Phase11MVP3.Services.Core;
global using Phase11MVP3.Services.Balance;
global using Phase11MVP3.Services.Inventory;
global using Phase11MVP3.DataAccess.Inventory;
global using Phase11MVP3.Utilities;
global using Phase11MVP3.Services.Upgrades;
global using Phase11MVP3.Services.Progression;
global using Phase11MVP3.Services.Catalog;
global using Phase11MVP3.Services.Store;
global using Phase11MVP3.Services.Items;
global using Phase11MVP3.Services.InstantUnlimited;
global using Phase11MVP3.Services.TimedBoosts;
global using Phase11MVP3.Services.OutputAugmentation;
global using Phase11MVP3.Services.Rentals;
global using rs1 = Phase11MVP3.Utilities.RandomUtilities;
